image: gitpod/workspace-dotnet

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-runtime
    - ms-dotnettools.blazorwasm-companion
    - kevin-chatham.aspnetcorerazor-html-css-class-completion
    - ms-dotnettools.csdevkit